version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
